language: go
go:
- 1.11
install:
- go get -t -v ./...
- go get -v github.com/codeclimate/test-reporter
before_script:
- test-reporter before-build
script:
- if [[ $(gofmt -l $(find . -name '*.go' | grep -v vendor)) ]]; then
  echo "Found un-formatted go files. Run go fmt ./...";
  exit 1;
  fi
- go vet ./...
- go test -coverprofile=c.out -covermode=atomic $(go list ./... | grep -v vendor)
after_script:
- test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
