language: go
go:
- 1.9
install:
- go get -t -v ./...
- go get -v github.com/codeclimate/test-reporter
before_script:
- test-reporter before-build
script:
- "./test.sh"
after_script:
- test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
