addons:
  code_climate:
    repo_token:
      secure: "jf45MmJOotsBQ7xjpCt9Zv8B1cq7m6kY//3kBd+f9PYEQ6BE4wBuVDG5+SocUaVfl6HqsW7hchvFKoYS4liA6YG5QNvckZPq5iAq8MbNg7z3/my5CZpL/p90O/p1I0XxKwsLCak7cKSQudYW/fUIXGcyPZinlegjAJd5O62RAHMRjPpq8O6hMXu9AfA9yqH1PlYUYlrQ8tWCTrUpEUoDDEXa0s+ojQpbch8X/RQ1Wq3VzIjVdsZTgdheWyhal+nOJN29cbqDAN7l9ipYE8CqJMTay5k0HUtu3eXN9wr5vj4QTSl9NN0YRNrLN/CuUsD3hWyatd8+7BMkZvhlC2WFQqLPns6kJFslC15zuODkiNzwn+ggvndnv/BaE6P+odB+5yaSOGSqiGPvQ6iEOHDg4KbvoINQcQAGo4T40V7/QCseZClhBrtGO5MfQ5i5HiyqVI4s8FXA4np63KB9gzcglm4NsF9bnXTGMxNVjR8/F2U38XIJ1w7Lme1NXqdPwbGe8LbMObjnBDmE4gxggCGSHC5+KgG25bRdh8ObHNuYEiuXbTGySoRt61MuYtzGFDw5V7JCe4JKrfgtXfRMrgQfpGUduFtdJGP0Yr/FYwTNxx+KKEH/nncx7gr35NzuI+6/yuGF704lBTWymCoo+efroOWFKr+616CZTIRSHmlCO6U="
language: go
go:
- 1.9
install:
- go get -t -v ./...
- go get -v github.com/codeclimate/test-reporter
before_script:
- test-reporter before-build
script:
- "./test.sh"
after_script:
- test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
